### ISSUE TITLE
random generating seeds bug 

### ISSUE THREAD

**Issue by Skulblaka17** [turntekGodhead/ori_coop_server#5]
Sometimes i try to create a seed (and its spoiler) but and error occurs. the server display page with error 500 and it is unable to complete the request. In order to have a seed u need to close the page, reopen it and make another seed, even of the same type, and the server generate it normally. 
This strange error occur randomly so i can't say what cause it... if time or another variable in the generating process that goes crazy.

**Comment by turntekGodhead** [comment]
fixed with timeout increase and the global culling.
